### ISSUE TITLE
Error of initializing class

### ISSUE THREAD

**Issue by NurgisaA** [ggindinson/aiogram_widgets#2]
Error trying to play the example. Requires router. If the router is transferred, the message is displayed but the inline buttons do not work.

`TypeError: TextPaginator.__init__() missing 1 required positional argument: 'router'`

```
@router.message(F.text == "/test")
async def text_pagination(message: Message,):
    text_data = [
        f"I am string number {i}"
        for i in range(1, 1001)
    ]

    paginator = TextPaginator(
        data=text_data,
    )

    current_text_chunk, reply_markup = paginator.current_message_data

    await message.answer(
        text=current_text_chunk,
        reply_markup=reply_markup,
    )
```

**Comment by NurgisaA** [comment]
`    await dp.start_polling(bot, allowed_updates=["message", "callback_query"])
`
Sorry, I forgot to add callback_query.

**Comment by ggindinson** [comment]
> ` await dp.start_polling(bot, allowed_updates=["message", "callback_query"])` Sorry, I forgot to add callback_query.

You can pass `dp.resolve_used_update_types()` into `allowed_updates` param to **prevent** such errors in future!
